name: Terraform Apply

on:
  workflow_dispatch:  # manual trigger

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: apply-approval  # requires lead approval via GitHub Environment

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init \
          -backend-config="bucket=terraform-state-pratyushaa94" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
