name: Terraform Backend Setup

on:
  push:
    branches:
      - main

jobs:
  create-s3-backend:
    name: 'Create Backend S3 Bucket Only'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: "terraform-state-pratyushaa94"

    steps:
      - name: Create S3 Bucket for Backend
        run: |
          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            aws s3api create-bucket --bucket $BUCKET_NAME --region $AWS_DEFAULT_REGION

            aws s3api put-bucket-versioning \
              --bucket $BUCKET_NAME \
              --versioning-configuration Status=Enabled

            aws s3api put-bucket-encryption \
              --bucket $BUCKET_NAME \
              --server-side-encryption-configuration '{
                "Rules": [
                  {
                    "ApplyServerSideEncryptionByDefault": {
                      "SSEAlgorithm": "AES256"
                    }
                  }
                ]
              }'
          else
            echo "Bucket already exists."
          fi
