name: Terraform Plan with Cost Estimate

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Plan and Cost Analysis'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost cost estimate
        run: |
          infracost breakdown --path . \
            --format json \
            --show-skipped \
            --out-file infracost.json

      - name: Post Infracost comment
        uses: infracost/actions@v1
        with:
          path: infracost.json
          behavior: update
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Commented apply step for later use
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -var-file="terraform.tfvars"
