name: Terraform Plan Only

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Print Estimated Cost for S3 with Versioning
        run: |
          echo "###  Estimated Cost Summary" >> $GITHUB_STEP_SUMMARY
          echo "-  **S3 Bucket (Standard + Versioning):**" >> $GITHUB_STEP_SUMMARY
          echo "  - \$0.023 per GB stored/month" >> $GITHUB_STEP_SUMMARY
          echo "  - Each object version is stored and billed separately" >> $GITHUB_STEP_SUMMARY
          echo "  - Consider adding lifecycle rules to delete older versions to reduce cost" >> $GITHUB_STEP_SUMMARY

      # Uncomment this to apply automatically (optional)
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -var-file="terraform.tfvars"
